name: Cypress Automated Tests
on: [push]
permissions:
  contents: write
  pages: write
jobs:
  setup:
    name: Install & pre-test ðŸ›  
    runs-on: ubuntu-latest    
    strategy:
      fail-fast: false 
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        uses: cypress-io/github-action@v3
        with:
          runTests: false
  execution:
    name: Execution â³
    needs: setup
    strategy:
      fail-fast: false
      matrix:
#         os: [ubuntu-latest, ubuntu-22.04, ubuntu-20.04]
#         ci_node_total: [5]
#         ci_node_index: [1,2,3,4,5]
        containers: [ 0, 1, 2, 3, 4, 5 ]
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
#       - name: Docker-compose run
#         run: docker-compose -f ./docker-compose.full.yml up -d
#       - name: Read file if it exists?
#         uses: mathiasvr/command-output@v1
#         id: cmd
#         with:
#           run: node cypress-partial.js 5 1

#       - run: echo Command succeeded 
#         if: ${{ steps.cmd.outputs.stdout }}
      - run: |
         echo "specs=$(node cypress-partial.js 6 ${{ matrix.containers }})" >> $GITHUB_ENV
      #  id: tests

      - name: Cypress run 
        uses: cypress-io/github-action@v3
        with:
#           command: "npx percy exec -- npm run sorry-cypress-dashboard"
          command: npx cypress run --spec ${{ env.specs }}
        env:
          CYPRESS_API_URL: ${{ secrets.CYPRESS_API_URL }}
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}




















